title : Catherine Weaver Portfolio
description: Catherine Weaver is a mechanical engineer who is interested in applying state-of-the-art algorithms from control systems and computer science to the world around us.She specializes in autonomous vehicle racing, model-based control, and reinforcement learning.
show_github_link: False

remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
